"""Added draft of the category table.

Revision ID: 13759b921421
Revises: a482ec58621e
Create Date: 2021-12-06 12:41:00.449596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13759b921421'
down_revision = 'a482ec58621e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('page_title', sa.String(), nullable=False),
    sa.Column('page_description', sa.Text(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
